language: node_js
node_js:
- 12.16.1
deploy:
  provider: gae
  cleanup : false
  keyfile: client-secret.json
  project: modern-venture-280118
before_install:
- openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
  -in client-secret.json.enc -out client-secret.json -d
