services:
- docker
cache:
- directories:
    - ${HOME}/google-cloud-sdk


before_script:
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi

script:
- source ${HOME}/google-cloud-sdk/path.bash.inc
- echo "$GCLOUD_SERVICE_KEY_STG" | base64 --decode > ${HOME}/gcloud-service-key.json
- gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
- gcloud components install kubectl
- gcloud container clusters get-credentials $GKE_cluster_name --zone $GKE_zone --project $GKE_project_id
- docker build -t hi .